[package]
name = "graphics"
version = "0.0.1"
authors = ["AidoP <aidop@me.com>"]
edition = "2018"

[features]
<<<<<<< HEAD
#default = ["vulkan"]
=======
>>>>>>> 09c4cd26e169dc1f496bcde055f47741c3a155c4
vulkan = ["vulkano"]
fbdev = []

[dependencies.sdl2]
version = "0.32.2"
features = ["bundled", "static-link"]   # Statically link and build SDL2 from source

[dependencies]
vulkano = { version = "0.16.0", optional = true }
memory = { path = "../memory" }
