[package]
name = "memory"
version = "0.0.1"
authors = ["AidoP <aidop@me.com>", "Kazuna Nakama <kazunanakama@gmail.com>", "Alice Micheloni <alicemicheloni@tutanota.com>"]
edition = "2018"

[dependencies]
