[package]
name = "cpu"
version = "0.0.1"
authors = ["Guilherme Torres <guilhermetorres97@gmail.com>", "AidoP <aidop@me.com>", "Kazuna Nakama <kazunanakama@gmail.com>", "Alice Micheloni <alicemicheloni@tutanota.com>"]
edition = "2018"

[dependencies]
memory = { path = "../memory" }
